#!/usr/bin/env python3
"""fetch_skycultures.py — pull indigenous sky-culture directories verbatim
from the official Stellarium/stellarium-skycultures GitHub repository.

Every constellation, star name, and description this project shows comes
from that repository, as-is. This script never invents, translates,
"completes", or edits cultural content — it is a byte-for-byte copy of
what upstream publishes, including each culture's `description.md`
(required — it carries attribution/authorship/license) and any
`illustrations/` directory.

Usage (importable):

    from fetch_skycultures import fetch_culture
    fetch_culture("maori", Path("web/public/skycultures"))

Usage (CLI):

    python scripts/fetch_skycultures.py --dest web/public/skycultures \\
        maori hawaiian_starlines tongan anutan tukano tupi lokono \\
        northern_andes aztec inuit navajo blackfoot kamilaroi boorong western

Network approach: one GitHub "git trees" API call lists every file path in
the whole repo (recursive=1); each culture's files are then downloaded
individually from raw.githubusercontent.com. This keeps the script to a
single GitHub API call regardless of how many cultures are fetched
(unauthenticated API requests are rate-limited to 60/hour; raw file
downloads are not subject to that limit).

No caching is implemented — every run re-fetches the repo tree and every
requested culture's files fresh from upstream. If that ever needs to
change, add caching explicitly and document it here.

The CLI also syncs data/taxonomy.json (hand-authored source data, not
generated by this script — see that file) to web/public/taxonomy.json so
the browser can fetch /taxonomy.json directly. This is a plain file copy,
never a rewrite of its contents, and deliberately does not touch
web/vite.config.js.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

REPO_OWNER = "Stellarium"
REPO_NAME = "stellarium-skycultures"
DEFAULT_REF = "master"
USER_AGENT = "indigenous-stellarium-fetch-skycultures/1.0"

TREE_API_URL = (
    f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/git/trees/{{ref}}"
    "?recursive=1"
)
RAW_FILE_URL = (
    f"https://raw.githubusercontent.com/{REPO_OWNER}/{REPO_NAME}/{{ref}}/{{path}}"
)

DEFAULT_TIMEOUT = 30

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_TAXONOMY_SRC = REPO_ROOT / "data" / "taxonomy.json"
DEFAULT_TAXONOMY_DEST = REPO_ROOT / "web" / "public" / "taxonomy.json"


class FetchError(RuntimeError):
    """Raised when upstream doesn't have what we asked for, or its data
    doesn't match the documented sky-culture schema. Deliberately loud —
    a half-written culture directory is worse than a crash."""


def _http_get(url: str, timeout: int) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.read()
    except urllib.error.HTTPError as e:
        raise FetchError(f"HTTP {e.code} fetching {url}") from e
    except urllib.error.URLError as e:
        raise FetchError(f"network error fetching {url}: {e.reason}") from e


def fetch_repo_tree(ref: str = DEFAULT_REF, timeout: int = DEFAULT_TIMEOUT) -> list[dict[str, Any]]:
    """Fetch the full recursive file listing of stellarium-skycultures via
    the GitHub git-trees API (one request, regardless of culture count)."""
    url = TREE_API_URL.format(ref=ref)
    raw = _http_get(url, timeout=timeout)
    data = json.loads(raw)
    if data.get("truncated"):
        raise FetchError(
            "GitHub tree listing was truncated (repo too large for a single "
            "recursive call) — fetch_skycultures.py needs a paging fallback"
        )
    return data["tree"]


def _validate_index_schema(culture_id: str, index: dict[str, Any]) -> None:
    """Sanity-check index.json against the schema documented in
    docs/DESIGN.md. Raises FetchError (not silently drops data) if
    upstream doesn't match — the repo is live and may have changed since
    the schema was verified.

    Two real-world variations, confirmed against live upstream data while
    building this script, are treated as valid (not documented in
    docs/DESIGN.md's "verified technical facts" — see task-3-report.md):

    - A constellation entry may have no 'lines' key at all. "Dark
      constellations" (e.g. kamilaroi's 'Gawaargay', traced in Milky Way
      dust lanes rather than star-to-star lines) are defined only by an
      'image' overlay with anchors. Absence of lines there is real data,
      not a malformed entry.
    - A polyline may contain a leading style-tag string (observed:
      "thin", e.g. western's 'CON western CMa') ahead of its HIP numbers,
      not just ints. Non-int elements are treated as style tags and
      skipped; every remaining element must still be an int.
    """
    if index.get("id") != culture_id:
        raise FetchError(
            f"{culture_id}: index.json 'id' field is {index.get('id')!r}, "
            f"expected {culture_id!r}"
        )
    constellations = index.get("constellations")
    if not isinstance(constellations, list) or len(constellations) == 0:
        raise FetchError(
            f"{culture_id}: index.json has no non-empty 'constellations' list"
        )
    for con in constellations:
        if "lines" not in con:
            continue  # dark constellation / image-only entry — valid
        lines = con.get("lines")
        if not isinstance(lines, list) or len(lines) == 0:
            raise FetchError(
                f"{culture_id}: constellation {con.get('id')!r} has a "
                "'lines' key that isn't a non-empty list"
            )
        for polyline in lines:
            if not isinstance(polyline, list) or len(polyline) == 0:
                raise FetchError(
                    f"{culture_id}: constellation {con.get('id')!r} has a "
                    "'lines' entry that isn't a non-empty list"
                )
            hip_values = [v for v in polyline if not isinstance(v, str)]
            if not hip_values or not all(isinstance(v, int) for v in hip_values):
                raise FetchError(
                    f"{culture_id}: constellation {con.get('id')!r} has a "
                    "'lines' polyline with a non-int, non-style-tag element"
                )


def fetch_culture(
    culture_id: str,
    dest: Path | str,
    *,
    ref: str = DEFAULT_REF,
    tree: list[dict[str, Any]] | None = None,
    timeout: int = DEFAULT_TIMEOUT,
) -> Path:
    """Fetch one sky-culture directory from stellarium-skycultures into
    ``dest/<culture_id>/``, verbatim — every file upstream has under that
    directory (index.json, description.md, illustrations/, doc/, po/,
    loose images, etc.), nothing added or removed.

    Raises FetchError if the culture id doesn't exist upstream, or if its
    index.json doesn't have the documented shape (id/constellations/lines).
    Writes to a temp directory first and only replaces the destination on
    full success, so a failed fetch never leaves a half-written culture
    directory behind.
    """
    if tree is None:
        tree = fetch_repo_tree(ref=ref, timeout=timeout)

    prefix = f"{culture_id}/"
    files = [
        entry
        for entry in tree
        if entry.get("type") == "blob" and entry["path"].startswith(prefix)
    ]
    if not files:
        raise FetchError(
            f"culture id {culture_id!r} not found in "
            f"{REPO_OWNER}/{REPO_NAME}@{ref} (no files under {prefix!r})"
        )

    dest = Path(dest)
    culture_dest = dest / culture_id
    tmp_dest = dest / f".{culture_id}.fetching"
    if tmp_dest.exists():
        shutil.rmtree(tmp_dest)
    tmp_dest.mkdir(parents=True)

    try:
        for entry in files:
            rel_path = entry["path"][len(prefix):]
            out_path = tmp_dest / rel_path
            out_path.parent.mkdir(parents=True, exist_ok=True)
            raw_url = RAW_FILE_URL.format(ref=ref, path=entry["path"])
            out_path.write_bytes(_http_get(raw_url, timeout=timeout))

        index_path = tmp_dest / "index.json"
        if not index_path.is_file():
            raise FetchError(f"culture {culture_id!r} has no index.json upstream")
        with open(index_path) as f:
            index = json.load(f)
        _validate_index_schema(culture_id, index)

        if not (tmp_dest / "description.md").is_file():
            raise FetchError(
                f"culture {culture_id!r} has no description.md upstream — "
                "attribution/license text is required, refusing to write a "
                "directory without it"
            )
    except Exception:
        shutil.rmtree(tmp_dest, ignore_errors=True)
        raise

    if culture_dest.exists():
        shutil.rmtree(culture_dest)
    tmp_dest.rename(culture_dest)
    return culture_dest


def sync_taxonomy(
    src: Path = DEFAULT_TAXONOMY_SRC, dest: Path = DEFAULT_TAXONOMY_DEST
) -> Path:
    """Copy the hand-authored data/taxonomy.json to web/public/taxonomy.json
    so the browser can fetch /taxonomy.json directly at dev/build time,
    without wiring taxonomy handling into vite.config.js. This is a plain
    file copy — taxonomy.json's contents are authored by hand, never
    generated or edited here.
    """
    if not src.is_file():
        raise FetchError(f"taxonomy source not found: {src}")
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dest)
    return dest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Fetch indigenous sky-culture directories verbatim from "
            "Stellarium/stellarium-skycultures."
        )
    )
    parser.add_argument(
        "culture_ids",
        nargs="+",
        help="culture directory names in the upstream repo, e.g. maori tongan",
    )
    parser.add_argument(
        "--dest",
        required=True,
        type=Path,
        help="destination directory; each culture is written to <dest>/<id>/",
    )
    parser.add_argument("--ref", default=DEFAULT_REF, help="git ref (default: master)")
    args = parser.parse_args(argv)

    args.dest.mkdir(parents=True, exist_ok=True)

    print(f"Fetching repo file listing ({REPO_OWNER}/{REPO_NAME}@{args.ref}) ...")
    tree = fetch_repo_tree(ref=args.ref)

    failures: list[str] = []
    for culture_id in args.culture_ids:
        print(f"==> {culture_id}")
        try:
            culture_dir = fetch_culture(culture_id, args.dest, ref=args.ref, tree=tree)
        except FetchError as e:
            print(f"    FAILED: {e}", file=sys.stderr)
            failures.append(culture_id)
            continue
        n_files = sum(1 for _ in culture_dir.rglob("*") if _.is_file())
        print(f"    wrote {culture_dir} ({n_files} files)")

    try:
        taxonomy_dest = sync_taxonomy()
        print(f"\nSynced {DEFAULT_TAXONOMY_SRC} -> {taxonomy_dest}")
    except FetchError as e:
        print(f"\nWARNING: taxonomy sync skipped: {e}", file=sys.stderr)

    if failures:
        print(
            f"\n{len(failures)} culture(s) failed to fetch: {', '.join(failures)}",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
